### ISSUE TITLE
Roku deploy with args

### ISSUE THREAD

**Issue by iBicha** [rokucommunity/roku-deploy#102]
Allow options (perhaps in bsconfig.json) to specify args passed when launching, things like `mediaType` and `contentId`
To allow launching with deep link data directly.
It would be nice that brighterscript `require('brighterscript').ProgramBuilder` can take these launch arguments and pass them to the app on Roku.

**Comment by TwitchBronBron** [comment]
Yeah this would definitely be nice. 

@chrisdp It kinda feels like this does belong in roku-deploy, even though roku-deploy hasn't done any code modifications up to this point. It wouldn't be too much, just have the "scan for the main function()" task and then modify the main function to look something like this:
```brightscript
sub main(params) : params.append({mediaType: "<the value>", contentId: "<the value>"})
```

**Comment by iBicha** [comment]
I thought it could be done using ECP https://developer.roku.com/en-ca/docs/developer-program/debugging/external-control-api.md#general-ecp-commands

http://<IP of Roku>:8060/launch/[dev | channeID]?contentId=<content ID>&MediaType=<mediaType>

I would avoid modifying code if I could. But I'm too new to the system to know which is the best approach

**Comment by iBicha** [comment]
I was planning on both to be honest. Testing a deep link when the app is not running, and when the app is running. I have not considered any implications of run_as_process though.

The workflow I imagine is to have 3 (or more) launch settings in vs code
- One with no args
- One that starts the app with args
- One that sends the args to the currently running input

**Comment by TwitchBronBron** [comment]
Ok, so just for clarification,  this is the roku-deploy npm package which many developers use to create their zips and run sideloads from bash scripts or CI situations. 

Are you more interested in the vscode launch.json functionality? If so, we actually do already have some deep link support in vscode. See this docs link for more info: https://rokucommunity.github.io/vscode-brightscript-language/Debugging/deep-linking.html

**Comment by iBicha** [comment]
> Ok, so just for clarification, this is the roku-deploy npm package which many developers use to create their zips and run sideloads from bash scripts or CI situations.
> 
> Are you more interested in the vscode launch.json functionality? If so, we actually do already have some deep link support in vscode. See this docs link for more info: https://rokucommunity.github.io/vscode-brightscript-language/Debugging/deep-linking.html

I think this is exactly what I was talking about - I just thought that such functionality would be embedded in roku-deploy.

So this feature would only be relevant for people not using VS Code. Perhaps I should close this issue, and wait for someone to actually need this in roku-deploy itself.

Thanks a lot of your thorough responses!
