### ISSUE TITLE
Node x19 ECONNRESET when posting to device

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/roku-deploy#104]
As of node 19 the form post requests all fail with a ECONNRESET. This does not happen on 18.

**Comment by jordan-d-murphy** [comment]
This caused me endless frustration, thank you so much for calling this out @chrisdp you're the MVP we all needed 🙌
**Thank you!** 😊

**Comment by luis-soares-sky** [comment]
Any fix for this already identified? Suffering the same issue.

**Comment by TwitchBronBron** [comment]
Someone from the community recently mentioned that they were going to start working on it. 

https://rokudevelopers.slack.com/archives/CAJED581X/p1680545117363479?thread_ts=1680545117.363479&cid=CAJED581X

**Comment by TwitchBronBron** [comment]
This was fixed in #113
