### ISSUE TITLE
Add proper docs for full usage

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/roku-deploy#121]
We need proper documentation for:
 - how to use the new CLI
 - how to use the programmatic APIs
 - migration guide from v3 to v4

**Comment by MilapNaik** [comment]
- calling node API no longer loads JSON, 
- no more bsconfig.json, only rokudeploy.json
- name changes like .. also some have been removed and need to be called manually
- talk about why changes were made in v4
- new default file array
- anything else that a dev might need to change when upgrading

**Comment by MilapNaik** [comment]
#162

**Comment by MilapNaik** [comment]
#166
