### ISSUE TITLE
Upgrade to latest typescript

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/roku-deploy#147]
Upgrade to latest typescript and other tools (mocha, chai, etc...). 

```
npm install typescript@latest
```

Here are some good candidates:
 - typescript
 - chai
 - coveralls-next
 - eslint
 - mocha
 - nyc
 - q
 - rimraf
 - sinon
 - source-map-support
 - ts-node

**Comment by MilapNaik** [comment]
Won't be upgrading Chai because version 5.x is ESM-only

See: https://github.com/chaijs/chai/issues/1607

**Comment by MilapNaik** [comment]
Upgrading Sinon past v13 causes errors, upgrading chalk at all causes errors

**Comment by MilapNaik** [comment]
Upgrading eslint to v8 or @typescript-eslint/eslint-plugin/@typescript-eslint/parser to v6 causes errors

**Comment by MilapNaik** [comment]
(Most of these errors can be fixed if we ever decide to upgrade node past v14)
