### ISSUE TITLE
Update files array defaults

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/roku-deploy#58]
The default value for the `files` array was created a long time ago, and there are a few enhancements I think we should make. 

Here's my proposal for the updated files array.

```js
{
    "files": [
        //current files array
        "source/**/*.*",
        "components/**/*.*",
        "images/**/*.*:",
        "manifest",

        //new entries

        "locale/**/*",
        "fonts/**/*",

        //exclude root-level node_modules folder
        "!node_modules",
        //exclude markdown files, mac and windows fs database files
        "!**/*.{md,DS_Store,db}",
    ]
}
```

 Is there anything else I'm missing?

**Comment by philippe-elsass-deltatre** [comment]
Maybe `fonts/`, `libs/`?

**Comment by chrisdp** [comment]
> Maybe `fonts/`, `libs/`?

+1 for `fonts/` as this shows up in Rokus documentation and I think some samples. 
As for `libs/` I think a lot of SDK's tend to tell you to add it to the source folder some where or the files tend to be under components. So not sure if that one needs to be a default.

**Comment by TwitchBronBron** [comment]
Perhaps we should exclude files that get rejected by static analysis (such as *.md files), and also exclude filesystem database files like thumbs.db and .DS_Store.

**Comment by slheavner** [comment]
```
        //exclude root-level node_modules folder
        "!node_modules",
```

Just want to make sure this isn't a _little_ aggressive for anyone manually including npm dependencies that aren't using ropm. 

If a project adds something like `"node_modules/my-roku-module/dist/**/*.*"` would that still be included? I'm assuming it would if but I'm not keen on the implementation of the file resolution.

**Comment by chrisdp** [comment]
The defaults only applies when people do not define a files array. So if someone where to define a files array and add your example they would still work like it used to.

**Comment by TwitchBronBron** [comment]
Great question! 

In this situation, you would have to define your own files array anyway. In vscode, this would auto-populate the full default list, at which point you could customize it. The LAST entry in the list will win for any given file. So as long as `"node_modules/my-roku-module/dist/**/*.*"` showed up _after_ `"!**/node_modules/`, then they'd be good to go. 

If we don't exclude node_modules in the default, then any team that has node_modules next to their roku code could accidentally include the entirety of node_modules in the .zip that we build and upload to the device (this is a fairly common issue we see when people start complaining "my app took 3 minutes to upload")

**Comment by MilapNaik** [comment]
Done in #162
