### ISSUE TITLE
Don't normalize file patterns

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/roku-deploy#87]
Currently in `normalizeFilesArray`, we run the `src` string through `util.standardizePath()`. However, this could break glob escapes. All glob paths must use forward slash for directory separators. 

This is a breaking change, so it should be handled in v4.

**Comment by MilapNaik** [comment]
Done in https://github.com/rokucommunity/roku-deploy/pull/131

**Comment by MilapNaik** [comment]
Will close when v4 is merged

**Comment by TwitchBronBron** [comment]
Let's go ahead and close this now. it'll land in v1, but closing it helps us track that the work is finished.
