### ISSUE TITLE
allow means of excluding map file from zip; but maintaining in staging

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/roku-deploy#93]
.map files are required to facilitate debugging brighterscript files.
They should not be included in zips however, so we can exlclude them in vscode, using the files glob in the launch config.

However: 
 - the vscode debugger will not work if .map files are not present in the staging folder
 - forcing us to include them in the zip (as that's the only way to get them into the staging folder)
 - roku sideloading attempts compilation of these .map files, taking up to 1-2 seconds to do so, plus the extra time to copy them onto the device
 - this prevents us from reducing compile times :(

Can we please have a means of exlcuding .map files (or perhaps any glob of files) from the zip; while maintaining them in the staging folder?

**Comment by chrisdp** [comment]
@triwav should this be expanded externuous files?

This would then be used to reject .md, .map, and any others we know will fail static channel analysis as well. We talked about doing this in the past but never got around to it.

**Comment by TwitchBronBron** [comment]
We resolved this in the vscode extension in https://github.com/rokucommunity/roku-debug/pull/145. Closing this as I believe that's what the desired outcome was.
